# Generated by Django 5.2.11 on 2026-02-13 03:26

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('one_liner', models.CharField(blank=True, default='', max_length=300)),
                ('problem', models.TextField(blank=True, default='')),
                ('solution', models.TextField(blank=True, default='')),
                ('target_user', models.TextField(blank=True, default='')),
                ('revenue_model', models.TextField(blank=True, default='')),
                ('tech_stack_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('lifecycle_stage', models.CharField(choices=[('proposal', 'Proposal'), ('incubation', 'Incubation'), ('active_build', 'Active Build'), ('shipped', 'Shipped'), ('earning', 'Earning'), ('sunset', 'Sunset')], default='proposal', max_length=20)),
                ('proposal_ends_at', models.DateTimeField(blank=True, null=True)),
                ('incubation_started_at', models.DateTimeField(blank=True, null=True)),
                ('active_build_started_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('sunset_at', models.DateTimeField(blank=True, null=True)),
                ('production_url', models.URLField(blank=True, default='')),
                ('staging_url', models.URLField(blank=True, default='')),
                ('repo_url', models.URLField(blank=True, default='')),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('accepted_contributions', models.IntegerField(default=0)),
                ('unique_contributors', models.IntegerField(default=0)),
                ('first_revenue', models.BooleanField(default=False)),
                ('milestone_1_reached', models.BooleanField(default=False)),
                ('milestone_2_reached', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='founded_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects_project',
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_seed_team', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects_project_member',
                'unique_together': {('project', 'user')},
            },
        ),
    ]
