# Generated by Django 5.2.11 on 2026-02-13 03:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contributions', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KarmaLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('contribution_accepted', 'Contribution Accepted'), ('contribution_reverted', 'Contribution Reverted'), ('milestone_bonus', 'Milestone Bonus'), ('vesting', 'Vesting'), ('manual_adjustment', 'Manual Adjustment')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('formula_inputs', models.JSONField(blank=True, default=dict)),
                ('balance_after', models.DecimalField(decimal_places=4, max_digits=12)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contributions.contribution')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karma_ledger_entries', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karma_ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'karma_ledger',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='KarmaBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_karma', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('vested_karma', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('contribution_count', models.IntegerField(default=0)),
                ('last_contribution_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karma_balances', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karma_balances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'karma_balance',
                'unique_together': {('project', 'user')},
            },
        ),
    ]
