# Generated by Django 5.2.11 on 2026-02-13 03:26

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('acceptance_criteria', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('ideation', 'Ideation'), ('code', 'Code'), ('design', 'Design'), ('testing', 'Testing'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('governance', 'Governance')], max_length=20)),
                ('estimated_effort', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='M', max_length=2)),
                ('required_skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('karma_bounty', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('is_critical', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('claimed', 'Claimed'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('claim_expires_at', models.DateTimeField(blank=True, null=True)),
                ('extended_once', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
            options={
                'db_table': 'tasks_task',
            },
        ),
    ]
