# Generated by Django 5.2.11 on 2026-02-13 03:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('project_created', 'Project Created'), ('project_transitioned', 'Project Transitioned'), ('member_joined', 'Member Joined'), ('contribution_submitted', 'Contribution Submitted'), ('contribution_accepted', 'Contribution Accepted'), ('contribution_rejected', 'Contribution Rejected'), ('contribution_reverted', 'Contribution Reverted'), ('task_created', 'Task Created'), ('task_claimed', 'Task Claimed'), ('task_completed', 'Task Completed'), ('karma_awarded', 'Karma Awarded'), ('vote_cast', 'Vote Cast'), ('user_registered', 'User Registered'), ('verification_added', 'Verification Added')], max_length=40)),
                ('target_type', models.CharField(blank=True, default='', max_length=50)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor_username', models.CharField(blank=True, default='', max_length=150)),
                ('actor_avatar_url', models.URLField(blank=True, default='')),
                ('project_slug', models.CharField(blank=True, default='', max_length=100)),
                ('project_title', models.CharField(blank=True, default='', max_length=200)),
                ('summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to='projects.project')),
            ],
            options={
                'db_table': 'activity_event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='activity_ev_created_e69fcc_idx'), models.Index(fields=['project', '-created_at'], name='activity_ev_project_582e87_idx'), models.Index(fields=['actor', '-created_at'], name='activity_ev_actor_i_841e79_idx')],
            },
        ),
    ]
