# Generated by Django 5.2.11 on 2026-02-13 03:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('ideation', 'Ideation'), ('code', 'Code'), ('design', 'Design'), ('testing', 'Testing'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('governance', 'Governance')], max_length=20)),
                ('external_pr_url', models.URLField(blank=True, default='')),
                ('diff_summary', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_review', 'In Review'), ('changes_requested', 'Changes Requested'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('reverted', 'Reverted')], default='draft', max_length=20)),
                ('review_note', models.TextField(blank=True, default='')),
                ('base_karma', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('pioneer_multiplier', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('upvote_score', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('ai_multiplier', models.DecimalField(decimal_places=4, default=1, max_digits=10)),
                ('karma_awarded', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('karma_vested', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('reverted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='projects.project')),
                ('reverted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverted_contributions', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_contributions', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='tasks.task')),
            ],
            options={
                'db_table': 'contributions_contribution',
            },
        ),
    ]
